# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: 'Google auth'
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
         project_id: '${{ env.PROJECT_ID }}'
    - name: 'Docker auth'
      run: |-
         gcloud auth configure-docker europe-west12-docker.pkg.dev
    - name: 'Build and push container'
      run: |-
         docker build -t "europe-west12-docker.pkg.dev/personal-website-442420/cloud-run-source-deploy/personal-website:${{ github.sha }}" .
         docker push "europe-west12-docker.pkg.dev/personal-website-442420/cloud-run-source-deploy/personal-website:${{ github.sha }}"
    - name: 'Create release name'
      run: |-
         echo "RELEASE_NAME=${{ env.APP }}-${GITHUB_SHA::7}-${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}
    - name: 'Create Cloud Deploy release'
      uses: 'google-github-actions/create-cloud-deploy-release@v0'
      with:
         delivery_pipeline: 'charos_eu_pipeline'
         name: '${{ env.RELEASE_NAME }}'
         region: '${{ env.REGION }}'
         description: '${{ env.GITHUB_COMMIT_MSG }}'
         skaffold_file: 'config/skaffold.yaml'
         images: 'app=europe-west12-docker.pkg.dev/personal-website-442420/cloud-run-source-deploy:${{ github.sha }}'
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        delivery_pipeline: 'charos_eu_pipeline'
        service: 'personal-website'
        image: 'europe-west12-docker.pkg.dev/personal-website-442420/cloud-run-source-deploy:${{ github.sha }}'

  
